### ISSUE TITLE
Missing requirements for matlab

### ISSUE THREAD

**Issue by Melissa2661** [bmlklwx/EMS-superquadric_fitting#3]
Hello,

I just wanted to point out that you omitted some requirements from the matlab code: the Robotics System Toolbox and the Phased Array System Toolbox need to be installed in order for `multi_superquadric_script.m` to run without errors (on version R2023b).

![image](https://github.com/bmlklwx/EMS-superquadric_fitting/assets/81431180/2cba5a80-0568-45d7-80cc-0c53103c2365)

![image](https://github.com/bmlklwx/EMS-superquadric_fitting/assets/81431180/99f6a4d9-897c-48a9-bdb4-803e5fc213f5)

**Comment by bmlklwx** [comment]
Thanks for pointing out! I just added the corresponding utility functions so that the algorithm can run without those requirements.
