### ISSUE TITLE
The function point2angle is missing

### ISSUE THREAD

**Issue by zikai1** [bmlklwx/EMS-superquadric_fitting#4]
Hi,

Thanks for your excellent work! I'm currently working towards recovery of quadrics from range data, but when I tried to implement the normal superquadrics fitting algorithm implemented in `superquadricsFitting.m`, I encountered the following error:

<img width="1052" alt="1726892693873" src="https://github.com/user-attachments/assets/86d9b26f-53f9-49c5-a5bc-02aef967dd56">

It seems that the function `point2angle` is missing from the implementation. 

Would you kindly provide the missing function or any necessary additional code? Your assistance would be greatly appreciated.

Thank you in advance for your help.

Best regards.

**Comment by bmlklwx** [comment]
> Hi,
> 
> Thanks for your excellent work! I'm currently working towards recovery of quadrics from range data, but when I tried to implement the normal superquadrics fitting algorithm implemented in `superquadricsFitting.m`, I encountered the following error:
> 
> <img alt="1726892693873" width="1052" src="https://private-user-images.githubusercontent.com/37583980/369594779-86d9b26f-53f9-49c5-a5bc-02aef967dd56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTA2NTYsIm5iZiI6MTcyNzk5MDM1NiwicGF0aCI6Ii8zNzU4Mzk4MC8zNjk1OTQ3NzktODZkOWIyNmYtNTNmOS00OWM1LWE1YmMtMDJhZWY5NjdkZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIxMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTQ2MmM4NzNhODMyOTY3MmRjMmQ2ZjRiOWZiYTA5NzRmZmI1YzQyMjc1YmU5OWIxYjk0ODViOWJiMTcyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4zKZbWZSoWQ5wWc92Na-f2LofzN9umcoQSlQVaG1jgg">
> It seems that the function `point2angle` is missing from the implementation.
> 
> Would you kindly provide the missing function or any necessary additional code? Your assistance would be greatly appreciated.
> 
> Thank you in advance for your help.
> 
> Best regards.

Hi, sorry for my late reply. I have updated the superquadricsFitting.m, including 3 missing utility functions. Please let me know if there are still problems.

**Comment by zikai1** [comment]
Hi, thanks for your update. The code is running now.  Thank you again!
