### ISSUE TITLE
Bottle Point Cloud

### ISSUE THREAD

**Issue by pingpongballz** [bmlklwx/EMS-superquadric_fitting#5]
Hi, 

Amazing stuff! Just wanted to ask, are the point clouds for the water bottles in the paper available? Thanks! 😄

**Comment by bmlklwx** [comment]
The bottles come from the KIT ObjectModels dataset. You can download the items from [here](https://h2t-projects.webarchiv.kit.edu/Projects/ObjectModelsWebUI/index.php?section=listAll)

**Comment by pingpongballz** [comment]
Thank you!

One more thing, is there a way to save the results as a mesh?

Apologies, im not too familiar with this field.
